# pull official base image
FROM python:3.10.5-alpine3.16

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 and Pillow dependencies
RUN sed -i -e 's/https/http/' /etc/apk/repositories \
    && apk update \
    && apk add postgresql-dev \
    && apk add gcc python3-dev musl-dev \
    && apk add jpeg-dev \
    && apk add zlib-dev

# install dependencies
COPY . .
RUN pip install --upgrade pip
COPY ./requirements/* .
RUN pip install -r requirements/dev.txt

# copy entrypoint.sh
COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.dev.sh
RUN chmod +x /usr/src/app/entrypoint.dev.sh

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]
